---
- name: Execute VMware Automation PowerShell Scripts on Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Create Temp folder on Windows host
      win_file:
        path: C:\Temp
        state: directory

    - name: Copy PowerShell scripts to Windows host
      win_copy:
        src: "files/{{ item }}"
        dest: "C:\\Temp\\{{ item }}"
      loop:
        - Idrac_check.ps1
        - ESXi-SSH-Manager.ps1
        - Datastore-name-fixer.ps1
        - vcenters_cleanup.ps1
        - vmware-site-checker.ps1

    - name: Run Idrac_check.ps1
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\\Temp\\Idrac_check.ps1

    - name: Run ESXi-SSH-Manager.ps1
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\\Temp\\ESXi-SSH-Manager.ps1

    - name: Run Datastore-name-fixer.ps1
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\\Temp\\Datastore-name-fixer.ps1

    - name: Run vcenters_cleanup.ps1
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\\Temp\\vcenters_cleanup.ps1

    - name: Run vmware-site-checker.ps1
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\\Temp\\vmware-site-checker.ps1
